# This is a basic workflow to help you get started with Actions

name: Deploy to Heroku

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      heroku_app_name:
        required: true
        type: string
        description: The name of the Heroku app to deploy to
      heroku_email:
        type: string
        required: true
        description: The email address to use when creating a new Heroku app
      heroku_process_types:
        type: string
        required: false
        default: web
        description: The process types to deploy
  workflow_call:
    inputs:
      heroku_app_name:
        required: true
        type: string
      heroku_email:
        type: string
        required: true
      heroku_process_types:
        type: string
        required: false
        default: web
        description: The process types to deploy
    secrets:
      HEROKU_API_KEY:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Install Heroku CLI
        if: ${{ env.ACT }}
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

      - uses: akhileshns/heroku-deploy@v3.12.13 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ inputs.heroku_app_name }} # Must be unique in Heroku
          heroku_email: ${{ inputs.heroku_email }}
          justlogin: true

      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Release
        run: heroku container:release ${{ inputs.heroku_process_types }} -a ${{ inputs.heroku_app_name }}
