# This is a basic workflow to help you get started with Actions

name: Lint

on:
  workflow_dispatch:
    inputs:
      lint_command:
        required: false
        type: string
        default: pnpm lint-only
        description: The command for running lint
      package_manager:
        required: false
        type: string
        default: pnpm
        description: The package manager to use
      pnpm_version:
        required: false
        type: string
        default: "8"
        description: If using pnpm - which version to use
  workflow_call:
    inputs:
      lint_command:
        required: false
        type: string
        default: pnpm lint-only
      package_manager:
        required: false
        type: string
        default: pnpm
        description: The package manager to use
      pnpm_version:
        required: false
        type: string
        default: "8"
        description: If using pnpm - which version to use

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        id: checkout

      - uses: pnpm/action-setup@v2
        if: ${{ inputs.package_manager == 'pnpm' }}
        with:
          version: ${{ inputs.pnpm_version }}

      - uses: actions/setup-node@v3
        if: ${{ env.ACT }}
        with:
          node-version-file: .nvmrc

      - uses: actions/setup-node@v3
        if: ${{ !env.ACT }}
        with:
          node-version-file: .nvmrc
          cache: ${{ inputs.package_manager }}

      - name: Install dependencies (bun)
        run: ${{ inputs.package_manager }} install --frozen-lockfile --concurrent-scripts 1
        if: ${{ inputs.package_manager == 'bun' }}
        working-directory: ${{ inputs.working_directory }}

      - name: Install dependencies (npm)
        run: npm ci
        if: ${{ inputs.package_manager == 'npm' }}
        working-directory: ${{ inputs.working_directory }}

      - name: Install dependencies (others)
        run: ${{ inputs.package_manager }} install --frozen-lockfile
        if: ${{ inputs.package_manager != 'npm' && inputs.package_manager != 'bun' }}
        working-directory: ${{ inputs.working_directory }}

      - name: Lint
        run: ${{ inputs.lint_command }}
