name: Playwright Tests
on:
  workflow_call:
    inputs:
      repository:
        default: Kingstinct/schedulist-app
        description: The repository where the tests are
        required: false
        type: string
      PLAYWRIGHT_TEST_URL:
        default: https://master.web.schedulist.app/
        type: string
        required: false
  workflow_dispatch:
    inputs:
      PLAYWRIGHT_TEST_URL:
        description: URL to run playwright tests towards
        default: https://master.web.schedulist.app/
        type: string
        required: false
      repository:
        default: Kingstinct/schedulist-app
        description: The repository where the tests are
        required: false
        type: string

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: Kingstinct/schedulist-app

      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version-file: .nvmrc

      - name: Install dependencies
        run: yarn

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: PLAYWRIGHT_TEST_URL=${{ inputs.PLAYWRIGHT_TEST_URL }} npx playwright test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
