# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NPM Publish
run-name: ${{ inputs.description }} (${{ inputs.release_type }}) release by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      description:
        description: Description
        required: false
        type: string
      release_type:
        description: Release Type
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish-to-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm
          registry-url: https://registry.npmjs.org/
          scope: "@kingstinct"
      - run: git config user.name "$(git log -n 1 --pretty=format:%an)"
      - run: git config user.email "$(git log -n 1 --pretty=format:%ae)"
      - run: pnpm install --frozen-lockfile
      - run: echo "versionTag=`npm version ${{ github.event.inputs.release_type }} -m "%s ${{ github.event.inputs.description }}"`" >> $GITHUB_ENV
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - run: git push --follow-tags --no-verify
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.versionTag }} ${{ github.event.inputs.description }}
          tag_name: ${{ env.versionTag }}
          generate_release_notes: true
