# This is a basic workflow to help you get started with Actions

name: Test

on:
  push:
    branches:
      - "*" # matches every branch that doesn't contain a '/'
      - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch
      - "!main" # matches no branches
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    uses: ./.github/workflows/test-in-parallel.yml
    with:
      parellelism_count: 2
      test_command: npx jest
      package_manager: pnpm

  lint:
    uses: ./.github/workflows/lint.yml

  typecheck:
    uses: ./.github/workflows/typecheck.yml
