# This is a basic workflow to help you get started with Actions

name: Typecheck

on:
  workflow_dispatch:
    inputs:
      typecheck_command:
        required: false
        description: The command for running typechecks
        type: string
        default: tsc --noEmit
      package_manager:
        required: false
        description: The package manager to use
        type: string
        default: pnpm
  workflow_call:
    inputs:
      typecheck_command:
        required: false
        type: string
        default: tsc --noEmit
      package_manager:
        required: false
        type: string
        default: pnpm

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        id: checkout

      - uses: pnpm/action-setup@v2.2.2
        if: ${{ inputs.package_manager == 'pnpm' }}
        with:
          version: 7

      - uses: actions/setup-node@v2
        if: ${{ env.ACT }}
        with:
          node-version-file: .nvmrc

      - uses: actions/setup-node@v2
        if: ${{ !env.ACT }}
        with:
          node-version-file: .nvmrc
          cache: ${{ inputs.package_manager }}

      - name: Install deps
        id: install
        run: ${{ inputs.package_manager }} install

      - name: Lint
        run: ${{ inputs.typecheck_command }}
